# Generated by Django 4.1.4 on 2023-12-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='base/img/avatars/default_avatar.png', null=True, upload_to='base/img/avatars', verbose_name='Фото профілю'),
        ),
    ]
