# Generated by Django 4.1.4 on 2023-12-11 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='picture',
            field=models.FileField(null=True, upload_to='base/img/song-wrappers', verbose_name='Обгортка'),
        ),
    ]
